-- File: database/opstus.sql
-- OPSTUS Database Schema
-- Run this in phpMyAdmin

CREATE DATABASE IF NOT EXISTS `opstus_db` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `opstus_db`;

-- Drop tables if exist (for clean install)
DROP TABLE IF EXISTS `activity_log`;
DROP TABLE IF EXISTS `monthly_reports`;
DROP TABLE IF EXISTS `transactions`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `centers`;
DROP TABLE IF EXISTS `settings`;

-- Centers table
CREATE TABLE `centers` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `center_name` VARCHAR(255) NOT NULL,
    `location` VARCHAR(255) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Users table
CREATE TABLE `users` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `username` VARCHAR(100) NOT NULL UNIQUE,
    `email` VARCHAR(255) DEFAULT NULL,
    `password` VARCHAR(255) NOT NULL,
    `role` ENUM('super_admin', 'center_admin') NOT NULL DEFAULT 'center_admin',
    `center_id` INT DEFAULT NULL,
    `status` ENUM('active', 'blocked') NOT NULL DEFAULT 'active',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`center_id`) REFERENCES `centers`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Transactions table
CREATE TABLE `transactions` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `center_id` INT NOT NULL,
    `type` ENUM('income', 'expense') NOT NULL,
    `category` VARCHAR(100) DEFAULT NULL,
    `description` VARCHAR(500) DEFAULT NULL,
    `amount` DECIMAL(12,2) NOT NULL,
    `date` DATE NOT NULL,
    `month` INT NOT NULL,
    `year` INT NOT NULL,
    `created_by` INT DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`center_id`) REFERENCES `centers`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
    INDEX `idx_center_month_year` (`center_id`, `month`, `year`),
    INDEX `idx_type` (`type`)
) ENGINE=InnoDB;

-- Monthly reports table
CREATE TABLE `monthly_reports` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `center_id` INT NOT NULL,
    `month` INT NOT NULL,
    `year` INT NOT NULL,
    `total_income` DECIMAL(12,2) DEFAULT 0.00,
    `total_expense` DECIMAL(12,2) DEFAULT 0.00,
    `net_profit` DECIMAL(12,2) DEFAULT 0.00,
    `status` ENUM('pending', 'submitted') NOT NULL DEFAULT 'pending',
    `pdf_path` VARCHAR(500) DEFAULT NULL,
    `submitted_at` TIMESTAMP NULL DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`center_id`) REFERENCES `centers`(`id`) ON DELETE CASCADE,
    UNIQUE KEY `unique_center_month_year` (`center_id`, `month`, `year`)
) ENGINE=InnoDB;

-- Settings table
CREATE TABLE `settings` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `company_name` VARCHAR(255) DEFAULT 'OPSTUS',
    `tagline` VARCHAR(255) DEFAULT 'Smart Multi-Center Financial Management',
    `email` VARCHAR(255) DEFAULT 'admin@opstus.com',
    `logo` VARCHAR(255) DEFAULT 'logo.png',
    `auto_block_days` INT DEFAULT 5,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Activity log table
CREATE TABLE `activity_log` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT DEFAULT NULL,
    `action` VARCHAR(255) NOT NULL,
    `details` TEXT DEFAULT NULL,
    `ip_address` VARCHAR(45) DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Insert default settings
INSERT INTO `settings` (`company_name`, `tagline`, `email`, `logo`, `auto_block_days`)
VALUES ('OPSTUS', 'Smart Multi-Center Financial Management', 'admin@opstus.com', 'logo.png', 5);

-- Insert sample centers
INSERT INTO `centers` (`center_name`, `location`) VALUES
('Main Center', 'New York, NY'),
('West Branch', 'Los Angeles, CA'),
('East Branch', 'Chicago, IL');

-- NOTE: Default password for ALL users is: Admin@123
-- The hash below is generated by PHP password_hash('Admin@123', PASSWORD_DEFAULT)
-- We use a known working hash

-- Super Admin
INSERT INTO `users` (`name`, `username`, `email`, `password`, `role`, `center_id`, `status`) VALUES
('Super Administrator', 'superadmin', 'admin@opstus.com',
    '$2y$10$8K1p/a0dL1LXMIgoEDHrOeSvFcPna9QWqWGjlVfGU2UhFCs4N2mCa', 'super_admin', NULL, 'active');

-- Center Admins
INSERT INTO `users` (`name`, `username`, `email`, `password`, `role`, `center_id`, `status`) VALUES
('John Manager', 'center1', 'center1@opstus.com',
    '$2y$10$8K1p/a0dL1LXMIgoEDHrOeSvFcPna9QWqWGjlVfGU2UhFCs4N2mCa', 'center_admin', 1, 'active'),
('Jane Manager', 'center2', 'center2@opstus.com',
    '$2y$10$8K1p/a0dL1LXMIgoEDHrOeSvFcPna9QWqWGjlVfGU2UhFCs4N2mCa', 'center_admin', 2, 'active');

-- Insert sample transactions for demo
INSERT INTO `transactions` (`center_id`, `type`, `category`, `description`, `amount`, `date`, `month`, `year`, `created_by`) VALUES
(1, 'income', NULL, 'Student Fees Collection', 15000.00, CURDATE(), MONTH(CURDATE()), YEAR(CURDATE()), 2),
(1, 'income', NULL, 'Workshop Revenue', 5000.00, CURDATE(), MONTH(CURDATE()), YEAR(CURDATE()), 2),
(1, 'expense', 'Salary', 'Staff Salary', 8000.00, CURDATE(), MONTH(CURDATE()), YEAR(CURDATE()), 2),
(1, 'expense', 'Rent', 'Office Rent', 3000.00, CURDATE(), MONTH(CURDATE()), YEAR(CURDATE()), 2),
(1, 'expense', 'Electricity', 'Electricity Bill', 500.00, CURDATE(), MONTH(CURDATE()), YEAR(CURDATE()), 2),
(2, 'income', NULL, 'Course Fees', 12000.00, CURDATE(), MONTH(CURDATE()), YEAR(CURDATE()), 3),
(2, 'expense', 'Salary', 'Staff Salary', 6000.00, CURDATE(), MONTH(CURDATE()), YEAR(CURDATE()), 3),
(2, 'expense', 'Food', 'Cafeteria Supplies', 1500.00, CURDATE(), MONTH(CURDATE()), YEAR(CURDATE()), 3);